/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import { Float } from '@react-three/drei';
import { ErrorBoundary } from 'react-error-boundary';
import VercelSafeModelLoader from './VercelSafeModelLoader';

const ReactLogo = (props) => {
  return (
    <VercelSafeModelLoader
      modelPath="/models/react.glb"
      fallbackGeometry="torus"
      fallbackSize={[2, 0.5, 16, 100]}
      fallbackColor="#61dafb"
      position={[8, 8, 0]}
      scale={0.3}
      {...props}
    >
      {({ nodes, materials }) => (
        <Float floatIntensity={1}>
          <group position={[8, 8, 0]} scale={0.3} {...props} dispose={null}>
            <mesh
              geometry={nodes['React-Logo_Material002_0'].geometry}
              material={materials['Material.002']}
              position={[0, 0.079, 0.181]}
              rotation={[0, 0, -Math.PI / 2]}
              scale={[0.392, 0.392, 0.527]}
            />
          </group>
        </Float>
      )}
    </VercelSafeModelLoader>
  );
};

export default ReactLogo;
